<template>
	
<section class="py-4">

      <div>
        <table class="table-auto w-full">
          <thead>
            <tr class="text-xs text-gray-500 text-left" data-config-id="row0">
              <th class="flex items-center pl-6 py-4 font-medium">
				  
                <a class="flex items-center" href="#">
                  <span data-config-id="2-col1-1">Name</span>
               
                </a>
              </th>
              <th class="py-4 font-medium">
                <a class="flex items-center" href="#">
                  <span data-config-id="2-col1-2">Address</span>
                 
                </a>
              </th>              
			  <th class="py-4 font-medium">
                <a class="flex items-center" href="#">
                  <span data-config-id="2-col1-2">Size</span>
                 
                </a>
              </th>
              <th class="py-4 font-medium">
                <a class="flex items-center" href="#">
                  <span data-config-id="2-col1-3">Price</span>
                </a>
              </th>
              <th class="py-4 font-medium">
                <a class="flex items-center" href="#">
                  <span data-config-id="2-col1-4">Type</span>
              
                </a>
              </th>
              <th class="py-4 font-medium">
                <a class="flex items-center" href="#">
                  <span data-config-id="2-col1-5">Date</span>
                </a>
              </th>             
			   <th class="py-4 font-medium">
                <a class="flex items-center" href="#">
                  <span data-config-id="2-col1-5">Share</span>
                </a>
              </th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="listing in listings" :key="listing.index" class="text-xs bg-gray-50" data-config-id="row-1" @submit="submitHandler">
              <td class="flex items-center py-5 px-6 font-medium">
                <input  class="mr-3"  type="checkbox" checked>
                <!-- <input v-model="listingArray.index" class="mr-3"  type="checkbox" name="listingID" :value="listing.Id" checked> -->
                <p data-config-id="2-col2-1">{{ listing.Name }}</p>
              </td>
              <td class="font-medium" data-config-id="2-col2-2">{{ listing.ZibunAddress }}</td>
              <td class="font-medium" data-config-id="2-col2-2">{{ listing.PrivateAreaP }}</td>
              <td class="font-medium" data-config-id="2-col2-3">{{ listing.Price }}</td>
              <td class="font-medium" data-config-id="2-col2-3">
               {{ listing.TradeType }}
              </td>
              <td data-config-id="2-col2-5">{{ listing.UpdateDate |  luxon("yyyy-MM-dd") }}</td>          
			      <td data-config-id="2-col2-5" class="flex items-center">
					  <input class="text-center" type="checkbox" checked name="" id=""></td>
            </tr>            
            
            <tr v-for="scraped in discore" :key="scraped.index" class="text-xs bg-gray-50" data-config-id="row-1" @submit="submitHandler">
              <td class="flex items-center py-5 px-6 font-medium">
                <input class="mr-3"  type="checkbox" name="listingID" :value="scraped.uuid">
                <p data-config-id="2-col2-1">*{{ scraped.title }}</p>
              </td>
              <td class="font-medium" data-config-id="2-col2-2">{{ scraped.address }}</td>
              <td class="font-medium" data-config-id="2-col2-2">{{ scraped.floor_area }}</td>
              <td class="font-medium" data-config-id="2-col2-3">{{ scraped.price }}</td>
              <td class="font-medium" data-config-id="2-col2-3">
               {{ scraped.deposit }}
              </td>
              <td data-config-id="2-col2-5">{{ scraped.creation_date }}</td>          
			      <td data-config-id="2-col2-5" class="flex items-center">
					  <input class="text-center" type="checkbox" checked name="" id=""></td>
            </tr>
          </tbody>
        </table>
		<hr class="my-4">
		<button type="submit" class="w-auto px-6 py-4 border ml-4 border-gray-400 text-white border-box rounded leading-none bg-tgray-500 text-xs hover:bg-tgray-700" @click="submitHandler(listings)"><span class="formulate-input-element--submit--label">다음: 포트폴리오 생성 시작
</span></button>
      </div>
</section>
</template>
<script>
export default {
	data(){
		return{
				listings: [
  {
    "Id": "00baf6dd-1bfd-46a0-8002-59468d4de4ce",
    "TradeType": 2,
    "Price": 60000,
    "Monthly": null,
    "Floor": "11",
    "TotalFloor": "24",
    "Room": 3,
    "Memo": "",
    "CreateDate": "2021-06-25T16:19:01.000Z",
    "ManagerId": "47d5daf5-4bba-4641-92a9-13b357851dc0",
    "AddressId": null,
    "Type": 5,
    "Link": "언덕위에 있어서 경치가 좋은 매물입니다",
    "ItemId": "88806-2106004",
    "RoadAddress": "경기 광명시 가림일로 101",
    "ZibunAddress": "경기 광명시 철산동 625",
    "PlaceName": null,
    "Region1depthName": null,
    "Region2depthName": null,
    "Region3depthName": null,
    "Status": 0,
    "Name": "도덕파크타운2단지아파트",
    "PrivateAreaP": 24,
    "PrivateAreaM": 79.2,
    "PublicAreaP": 27,
    "PublicAreaM": 89.1,
    "BathRoom": 2,
    "Direction": 3,
    "ViewCount": 1,
    "UpdateDate": "2021-06-25T16:19:01.000Z",
    "Lat": 37.47019831757382,
    "Lng": 126.86571422195452,
    "ManageFee": 200000,
    "ManageFeeElectronic": null,
    "ManageFeeGas": null,
    "ManageFeeWater": null,
    "ManageFeeInternet": null,
    "ManageFeeTV": null,
    "Parking": 1,
    "Elevator": 1,
    "Loan": 1,
    "Pet": null,
    "OwnerName": null,
    "OwnerPhone": null,
    "TenantName": null,
    "TenantPhone": null,
    "ManagerName": null,
    "ManagerPhone": null,
    "OptionAir": null,
    "OptionRefrig": null,
    "OptionWasher": null,
    "OptionGas": null,
    "OptionInduct": null,
    "OptionMicrowave": null,
    "OptionBook": null,
    "OptionBed": null,
    "OptionCloth": 1,
    "OptionBoot": 1,
    "OptionSync": null,
    "OriginalId": null,
    "IncomeText": null
  },
  {
    "Id": "1764e5af-d716-4a66-b6de-a161fea39b56",
    "TradeType": 3,
    "Price": 20000,
    "Monthly": 350,
    "Floor": "3",
    "TotalFloor": "15",
    "Room": 1,
    "Memo": "",
    "CreateDate": "2021-06-14T08:47:03.000Z",
    "ManagerId": "47d5daf5-4bba-4641-92a9-13b357851dc0",
    "AddressId": null,
    "Type": 6,
    "Link": "뷰 좋은 곳 항상 잘 팔리는곳",
    "ItemId": "88806-2106001",
    "RoadAddress": "서울특별시 중구 세종대로16길 22",
    "ZibunAddress": "서울 중구 북창동 17-2",
    "PlaceName": null,
    "Region1depthName": "서울",
    "Region2depthName": "중구",
    "Region3depthName": "북창동",
    "Status": 0,
    "Name": "연세치과",
    "PrivateAreaP": 57,
    "PrivateAreaM": 188.1,
    "PublicAreaP": 32,
    "PublicAreaM": 105.6,
    "BathRoom": 1,
    "Direction": 3,
    "ViewCount": 3,
    "UpdateDate": "2021-06-25T16:14:15.000Z",
    "Lat": 37.5630538,
    "Lng": 126.9780905,
    "ManageFee": null,
    "ManageFeeElectronic": null,
    "ManageFeeGas": null,
    "ManageFeeWater": null,
    "ManageFeeInternet": null,
    "ManageFeeTV": null,
    "Parking": null,
    "Elevator": null,
    "Loan": null,
    "Pet": null,
    "OwnerName": null,
    "OwnerPhone": null,
    "TenantName": null,
    "TenantPhone": null,
    "ManagerName": null,
    "ManagerPhone": null,
    "OptionAir": null,
    "OptionRefrig": null,
    "OptionWasher": null,
    "OptionGas": null,
    "OptionInduct": null,
    "OptionMicrowave": null,
    "OptionBook": null,
    "OptionBed": null,
    "OptionCloth": null,
    "OptionBoot": null,
    "OptionSync": null,
    "OriginalId": null,
    "IncomeText": null
  },
  {
    "Id": "26b67a8e-fda4-454d-85f1-a258c986f078",
    "TradeType": 3,
    "Price": 2000,
    "Monthly": 120,
    "Floor": "15",
    "TotalFloor": "25",
    "Room": 1,
    "Memo": "수요 많은 파크하비오 입니다.\n젊은층 분들에게 훨씬 인기가 많아 금방 매물이 나갈것 같아요",
    "CreateDate": "2021-06-25T16:11:52.000Z",
    "ManagerId": "47d5daf5-4bba-4641-92a9-13b357851dc0",
    "AddressId": null,
    "Type": 4,
    "Link": "인기 좋은 급 매물입니다",
    "ItemId": "88806-2106003",
    "RoadAddress": "서울 송파구 송파대로 111",
    "ZibunAddress": "서울 송파구 문정동 618",
    "PlaceName": null,
    "Region1depthName": null,
    "Region2depthName": null,
    "Region3depthName": null,
    "Status": 0,
    "Name": "송파파크하비오푸르지오오피스텔",
    "PrivateAreaP": 15,
    "PrivateAreaM": 49.5,
    "PublicAreaP": 9.09,
    "PublicAreaM": 30,
    "BathRoom": 1,
    "Direction": 3,
    "ViewCount": 2,
    "UpdateDate": "2021-06-25T16:11:52.000Z",
    "Lat": 37.47971076036868,
    "Lng": 127.12480132351254,
    "ManageFee": 150000,
    "ManageFeeElectronic": 1,
    "ManageFeeGas": 1,
    "ManageFeeWater": 1,
    "ManageFeeInternet": 1,
    "ManageFeeTV": 1,
    "Parking": 1,
    "Elevator": 1,
    "Loan": null,
    "Pet": null,
    "OwnerName": null,
    "OwnerPhone": null,
    "TenantName": null,
    "TenantPhone": null,
    "ManagerName": null,
    "ManagerPhone": null,
    "OptionAir": 1,
    "OptionRefrig": 1,
    "OptionWasher": 1,
    "OptionGas": 0,
    "OptionInduct": 1,
    "OptionMicrowave": 1,
    "OptionBook": null,
    "OptionBed": 0,
    "OptionCloth": 1,
    "OptionBoot": 1,
    "OptionSync": null,
    "OriginalId": null,
    "IncomeText": null
  },
  {
    "Id": "7423c379-15f0-4dee-b4a6-7f376f14413f",
    "TradeType": 1,
    "Price": 190000,
    "Monthly": null,
    "Floor": "7",
    "TotalFloor": "32",
    "Room": 4,
    "Memo": "",
    "CreateDate": "2021-06-25T16:20:15.000Z",
    "ManagerId": "47d5daf5-4bba-4641-92a9-13b357851dc0",
    "AddressId": null,
    "Type": 5,
    "Link": "교통 접근성 좋은 4대문 안에 있는 매물",
    "ItemId": "88806-2106005",
    "RoadAddress": "서울 중구 서소문로9길 28",
    "ZibunAddress": "서울 중구 순화동 217",
    "PlaceName": null,
    "Region1depthName": null,
    "Region2depthName": null,
    "Region3depthName": null,
    "Status": 0,
    "Name": "덕수궁롯데캐슬오피스텔",
    "PrivateAreaP": 43,
    "PrivateAreaM": 141.9,
    "PublicAreaP": 50,
    "PublicAreaM": 165,
    "BathRoom": 2,
    "Direction": 5,
    "ViewCount": 12,
    "UpdateDate": "2021-06-25T16:20:15.000Z",
    "Lat": 37.563236441462,
    "Lng": 126.97033643868892,
    "ManageFee": 350000,
    "ManageFeeElectronic": null,
    "ManageFeeGas": null,
    "ManageFeeWater": null,
    "ManageFeeInternet": null,
    "ManageFeeTV": null,
    "Parking": 1,
    "Elevator": 1,
    "Loan": null,
    "Pet": null,
    "OwnerName": null,
    "OwnerPhone": null,
    "TenantName": null,
    "TenantPhone": null,
    "ManagerName": null,
    "ManagerPhone": null,
    "OptionAir": null,
    "OptionRefrig": null,
    "OptionWasher": null,
    "OptionGas": null,
    "OptionInduct": null,
    "OptionMicrowave": null,
    "OptionBook": null,
    "OptionBed": null,
    "OptionCloth": 1,
    "OptionBoot": 1,
    "OptionSync": null,
    "OriginalId": null,
    "IncomeText": null
  },
  {
    "Id": "8b4948be-faba-40fa-b243-fb07eb15ac72",
    "TradeType": 1,
    "Price": 170000,
    "Monthly": null,
    "Floor": "17",
    "TotalFloor": "32",
    "Room": 3,
    "Memo": "",
    "CreateDate": "2021-06-16T16:10:05.000Z",
    "ManagerId": "47d5daf5-4bba-4641-92a9-13b357851dc0",
    "AddressId": null,
    "Type": 5,
    "Link": "동탄 핫한 매물입니다 젊은 신혼부부 인기매물",
    "ItemId": "88806-2106002",
    "RoadAddress": "경기 화성시 동탄대로9길 19",
    "ZibunAddress": "경기 화성시 송동 693",
    "PlaceName": null,
    "Region1depthName": "서울",
    "Region2depthName": "용산구",
    "Region3depthName": "이태원동",
    "Status": 0,
    "Name": "동탄2하우스디더레이크아파트",
    "PrivateAreaP": 32,
    "PrivateAreaM": 105.6,
    "PublicAreaP": 27,
    "PublicAreaM": 89.1,
    "BathRoom": 2,
    "Direction": 4,
    "ViewCount": 10,
    "UpdateDate": "2021-06-25T16:13:21.000Z",
    "Lat": 37.17396472107375,
    "Lng": 127.10401032811814,
    "ManageFee": 300000,
    "ManageFeeElectronic": 0,
    "ManageFeeGas": 0,
    "ManageFeeWater": 0,
    "ManageFeeInternet": null,
    "ManageFeeTV": null,
    "Parking": 0,
    "Elevator": 1,
    "Loan": null,
    "Pet": null,
    "OwnerName": null,
    "OwnerPhone": null,
    "TenantName": null,
    "TenantPhone": null,
    "ManagerName": null,
    "ManagerPhone": null,
    "OptionAir": 0,
    "OptionRefrig": null,
    "OptionWasher": 0,
    "OptionGas": 1,
    "OptionInduct": null,
    "OptionMicrowave": null,
    "OptionBook": null,
    "OptionBed": null,
    "OptionCloth": 1,
    "OptionBoot": 1,
    "OptionSync": 1,
    "OriginalId": null,
    "IncomeText": null
  }],
  discore:
  [
    {
        "suid": "mkl94ap2",
        "user": 229489,
        "address": "서울특별시 강남구 역삼동 748-17",
        "pnu": "1168010100107480017",
        "lat": 37.4955343549891,
        "lng": 127.036477485565,
        "photo": "290d742ef2504912a741abac.jpg|98ed358229514c5e8c1f769f.jpg|",
        "distance": 565.9006520106699,
        "title": "역삼역 인근 신축부지 ",
        "text": "━━━━━━━━━━━━━━━━━━━━━━━━\n\nKS부동산중개법인은 \n\n세무 법무(법인설립) 감정평가 금융권대출 신축설계 \n대수선리모델링 시공 임대차 건물운영 재매각 까지 \n\n빌딩관련 최고의 컨설팅이 가능한 중개법인 입니다   \n\n실투자금액과 투자목적을 정리해서 문의해주시면 \n최고의 매물을 소개해드리겠습니다★ \n\n━━━━━━━━━━━━━━━━━━━━━━━━\n(주)케이에스부동산중개법인\n대표 : 김진영\n주소 : 서울시 강남구 도곡로37길 51, 1층\n등록번호: 11680201600139\n━━━━━━━━━━━━━━━━━━━━━━━━",
        "price": 530000,
        "deposit": 0,
        "monthly": 0,
        "address_open": 1,
        "building_name": "",
        "supply_area": 0,
        "sale_type": 0,
        "estate_type": 0,
        "state_type": 0,
        "deal_type": 0,
        "creation_date": "2021.12.03.16.39.02",
        "land_area": 259.3,
        "floor_area": 483.6,
        "floor_cnt": 3,
        "floor_total": 3,
        "completion_year": "1992",
        "e_rand_type": 4,
        "under_floor": 1,
        "land_purpose": 0,
        "c_price": 530000,
        "luid": "dccjxne",
        "price_min": -1,
        "price_max": -1,
        "block_code": 0,
        "block_date": null,
        "land_size_min": -1,
        "land_size_max": -1,
        "total_land_min": -1,
        "total_land_max": -1,
        "c_type": null,
        "logo": null,
        "private_land_min": -1,
        "private_land_max": -1,
        "e_rand_type_array": "''",
        "purchase_due": null,
        "user_name": "백상민",
        "user_position": "소속공인중개사",
        "auid": "dnszj2ke",
        "user_org": "",
        "user_photo": "491dcb479fde41bb89355936.jpg",
        "user_logo": null,
        "extend_date": null,
        "extend_cnt": 0,
        "show_expire": 0,
        "purpose": "대",
        "oddr": "서울특별시 강남구 역삼동",
        "like": 0,
        "comment": 0
    },
    {
        "suid": "ckn6dnzb",
        "user": 194715,
        "address": "서울특별시 서초구 반포동 731-30",
        "pnu": "1165010700107310030",
        "lat": 37.5051885878698,
        "lng": 127.0195890433,
        "photo": "58f1526e788d4163834de7a9.png|",
        "distance": 1347.6859255782317,
        "title": "신논현역 도보 7분 논현역 도보 10분거리 더블역세권 위치한 임차수요풍부",
        "text": "본 건물은 9호선 신논현역 도보 7분, 7호선 논현역 도보 10분 거리로 더블 역세권에 위치. \n본 건물은 사평대로 이면에 위치해있고 접근성이 좋아 임차수요가 풍부하 여 신축 후 높은 수익률을 기대 할 수 있음. \n신분당선 연장선(강남~신사 구간) 사업에 따른 논현역의 환승역세권 계획 은 이 지역에 주요 이슈이자 호재로 향후 가치상승을 기대 할 수 있음. ",
        "price": 480000,
        "deposit": 0,
        "monthly": 0,
        "address_open": 1,
        "building_name": "",
        "supply_area": 0,
        "sale_type": 0,
        "estate_type": 0,
        "state_type": 0,
        "deal_type": 0,
        "creation_date": "2021.11.12.00.45.00",
        "land_area": 228.1,
        "floor_area": 521.09,
        "floor_cnt": 3,
        "floor_total": 3,
        "completion_year": "1997",
        "e_rand_type": 4,
        "under_floor": 1,
        "land_purpose": 0,
        "c_price": 480000,
        "luid": "lyrbc3q",
        "price_min": -1,
        "price_max": -1,
        "block_code": 0,
        "block_date": null,
        "land_size_min": -1,
        "land_size_max": -1,
        "total_land_min": -1,
        "total_land_max": -1,
        "c_type": null,
        "logo": null,
        "private_land_min": -1,
        "private_land_max": -1,
        "e_rand_type_array": "''",
        "purchase_due": null,
        "user_name": "고낙영",
        "user_position": "팀장",
        "auid": "vpx65zqe",
        "user_org": "",
        "user_photo": "01d1eaa2e4844cf3a6e382f0.jpg",
        "user_logo": null,
        "extend_date": null,
        "extend_cnt": 0,
        "show_expire": 0,
        "purpose": "대",
        "oddr": "서울특별시 서초구 반포동",
        "like": 0,
        "comment": 0
    },
    {
        "suid": "itjuv3qb",
        "user": 15618,
        "address": "서울특별시 강남구 역삼동 616-7",
        "pnu": "1168010100106160007",
        "lat": 37.5038496212671,
        "lng": 127.028000618087,
        "photo": "edc7cfe7b4f143a488836eae.JPG|",
        "distance": 845.430433276034,
        "title": "역삼동 사옥용 신축부지",
        "text": "자세한 사항은 전화로 상담 부탁 드립니다.",
        "price": 1550000,
        "deposit": 0,
        "monthly": 0,
        "address_open": 1,
        "building_name": "",
        "supply_area": 0,
        "sale_type": 0,
        "estate_type": 0,
        "state_type": 0,
        "deal_type": 0,
        "creation_date": "2021.10.12.14.54.47",
        "land_area": 493.8,
        "floor_area": 192.46,
        "floor_cnt": 2,
        "floor_total": 2,
        "completion_year": "1976",
        "e_rand_type": 3,
        "under_floor": 1,
        "land_purpose": 0,
        "c_price": 1550000,
        "luid": "d1t9r9p",
        "price_min": -1,
        "price_max": -1,
        "block_code": 0,
        "block_date": null,
        "land_size_min": -1,
        "land_size_max": -1,
        "total_land_min": -1,
        "total_land_max": -1,
        "c_type": null,
        "logo": null,
        "private_land_min": -1,
        "private_land_max": -1,
        "e_rand_type_array": "''",
        "purchase_due": null,
        "user_name": "최숙희",
        "user_position": "이사",
        "auid": "gbn2fegf",
        "user_org": "강남부동산중개",
        "user_photo": "13f701d2a7494f529b90fee3.jpg",
        "user_logo": null,
        "extend_date": null,
        "extend_cnt": 0,
        "show_expire": 0,
        "purpose": "대",
        "oddr": "서울특별시 강남구 역삼동",
        "like": 0,
        "comment": 0
    },
    {
        "suid": "h5gop6zc",
        "user": 194715,
        "address": "서울특별시 강남구 역삼동 830-16",
        "pnu": "1168010100108300016",
        "lat": 37.4945009540812,
        "lng": 127.031934619254,
        "photo": "386822aa19d34a508e14c5ab.png|",
        "distance": 266.42406867101334,
        "title": "더블역세권인 강남역에서 도보5분 거리에 위치한 접근성 우수",
        "text": "본 건물은 더블역세권 강남역(2호선,신분당선) 에서 도보 5분 이내 거리에 위치하고 있어 가시성 및 접근성이 뛰어남. \n해당지역은 배후로 주거지역이 밀집되어 있어 수요층이 튼튼하고 유동인구 가 항시 풍부한 지역으로 신축시 공실 위험이 거의 없어 안정적인 건물 운영이 가능함. ",
        "price": 530000,
        "deposit": 0,
        "monthly": 0,
        "address_open": 1,
        "building_name": "",
        "supply_area": 0,
        "sale_type": 0,
        "estate_type": 0,
        "state_type": 0,
        "deal_type": 0,
        "creation_date": "2021.09.15.00.02.06",
        "land_area": 250.3,
        "floor_area": 499.86,
        "floor_cnt": 3,
        "floor_total": 3,
        "completion_year": "1991",
        "e_rand_type": 4,
        "under_floor": 1,
        "land_purpose": 0,
        "c_price": 530000,
        "luid": "wvopatq",
        "price_min": -1,
        "price_max": -1,
        "block_code": 0,
        "block_date": null,
        "land_size_min": -1,
        "land_size_max": -1,
        "total_land_min": -1,
        "total_land_max": -1,
        "c_type": null,
        "logo": null,
        "private_land_min": -1,
        "private_land_max": -1,
        "e_rand_type_array": "''",
        "purchase_due": null,
        "user_name": "고낙영",
        "user_position": "팀장",
        "auid": "vpx65zqe",
        "user_org": "",
        "user_photo": "01d1eaa2e4844cf3a6e382f0.jpg",
        "user_logo": null,
        "extend_date": null,
        "extend_cnt": 0,
        "show_expire": 0,
        "purpose": "대",
        "oddr": "서울특별시 강남구 역삼동",
        "like": 0,
        "comment": 0
    },
    {
        "suid": "rrhyupsu",
        "user": 15618,
        "address": "서울특별시 서초구 서초동 ",
        "pnu": "1165010800",
        "lat": 37.49293879298256,
        "lng": 127.02319282194121,
        "photo": "01692689861341cf8f2631b6.png|",
        "distance": 1218.8991153657742,
        "title": "사정이 있어 급매로 매매합니다.",
        "text": "10m도로와 정원이 있는 단독주택을 용도변경하여 \n매매하는 조건임.\n자세한 사항은 전화로 문의 부탁드립니다.",
        "price": 420000,
        "deposit": 0,
        "monthly": 0,
        "address_open": 0,
        "building_name": "",
        "supply_area": 0,
        "sale_type": 0,
        "estate_type": 0,
        "state_type": 0,
        "deal_type": 0,
        "creation_date": "2021.08.23.15.55.08",
        "land_area": 330.1,
        "floor_area": 328.23,
        "floor_cnt": 2,
        "floor_total": 2,
        "completion_year": "1989",
        "e_rand_type": 3,
        "under_floor": 1,
        "land_purpose": 0,
        "c_price": 420000,
        "luid": null,
        "price_min": -1,
        "price_max": -1,
        "block_code": 0,
        "block_date": null,
        "land_size_min": -1,
        "land_size_max": -1,
        "total_land_min": -1,
        "total_land_max": -1,
        "c_type": null,
        "logo": null,
        "private_land_min": -1,
        "private_land_max": -1,
        "e_rand_type_array": "''",
        "purchase_due": null,
        "user_name": "최숙희",
        "user_position": "이사",
        "auid": "gbn2fegf",
        "user_org": "강남부동산중개",
        "user_photo": "13f701d2a7494f529b90fee3.jpg",
        "user_logo": null,
        "extend_date": "2021.11.24.14.15.03",
        "extend_cnt": 1,
        "show_expire": 0,
        "purpose": "대",
        "oddr": "서울특별시 서초구 서초동",
        "zoom": 5,
        "circle": 600,
        "add_pnus": "",
        "like": 0,
        "comment": 0
    },
    {
        "suid": "u29avq2v",
        "user": 15618,
        "address": "서울특별시 서초구 서초동 ",
        "pnu": "1165010800",
        "lat": 37.50017619122823,
        "lng": 127.02684364605729,
        "photo": "fecc686cbc5b4038b5f60703.PNG|",
        "distance": 462.31079966598514,
        "title": "투자가치 최고",
        "text": "자세한 사항은 전화로 문의 부탁드립니다.",
        "price": 7000000,
        "deposit": 0,
        "monthly": 0,
        "address_open": 0,
        "building_name": "",
        "supply_area": 0,
        "sale_type": 0,
        "estate_type": 0,
        "state_type": 0,
        "deal_type": 0,
        "creation_date": "2021.07.20.18.04.00",
        "land_area": 670,
        "floor_area": 3715.9,
        "floor_cnt": 9,
        "floor_total": 9,
        "completion_year": "1996",
        "e_rand_type": 4,
        "under_floor": 2,
        "land_purpose": 0,
        "c_price": 7000000,
        "luid": null,
        "price_min": -1,
        "price_max": -1,
        "block_code": 0,
        "block_date": null,
        "land_size_min": -1,
        "land_size_max": -1,
        "total_land_min": -1,
        "total_land_max": -1,
        "c_type": null,
        "logo": null,
        "private_land_min": -1,
        "private_land_max": -1,
        "e_rand_type_array": "''",
        "purchase_due": null,
        "user_name": "최숙희",
        "user_position": "이사",
        "auid": "gbn2fegf",
        "user_org": "강남부동산중개",
        "user_photo": "13f701d2a7494f529b90fee3.jpg",
        "user_logo": null,
        "extend_date": "2021.10.19.16.32.46",
        "extend_cnt": 1,
        "show_expire": 0,
        "purpose": "대",
        "oddr": "서울특별시 서초구 서초동",
        "zoom": 5,
        "circle": 600,
        "add_pnus": "",
        "like": 0,
        "comment": 0
    },
],
				listingArray: [],
				allSelected: false,
		}
	},
	    methods: {
        selectAll() {
            this.listingArray = [];

            if (!this.allSelected) {
                for (this.listing in this.listings) {
                    this.listingArray.push(this.listings[this.listing].Id);
                }
            }
        },

    async submitHandler (data) {
      await this.$localForage.setItem('selListings', data)
      this.$router.push('/app')
    },
  
    }
}
</script>